import Sidebar from '@/components/ui/sidebar';
import { Metadata } from 'next';
import React, { ReactNode } from 'react'

export const metadata: Metadata = {
    title: "DailyFy, Seu Espaço de Anotações Pessoais!",
    description: "Generated by create next app",
};

export default function AppLayout({children}: {children: ReactNode}) {
  return (
    <main className='w-full min-h-screen flex'>
        <Sidebar/>
        {children}
    </main>
  )
}
